# Generated by Django 2.0.10 on 2019-02-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名前を入力して下さい', max_length=30, verbose_name='名前')),
                ('furi', models.CharField(help_text='名前のフリガナを入力してください', max_length=30, verbose_name='フリガナ')),
                ('email', models.EmailField(default='', help_text='メールアドレスを入力してください', max_length=255, unique=True, verbose_name='メールアドレス')),
                ('memo', models.TextField(blank=True, help_text='参加人数が複数の場合や遅れて参加の場合は記入してください', verbose_name='メモ')),
            ],
        ),
    ]
