# Generated by Django 2.0.10 on 2019-04-10 14:39

from django.db import migrations, models
import pollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maildata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='連絡日・時間')),
                ('mail_to', models.EmailField(max_length=254, verbose_name=pollapp.models.Guest)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='', help_text='メールアドレスを入力してください', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='furi',
            field=models.CharField(help_text='名前のフリガナを入力してください', max_length=30),
        ),
        migrations.AlterField(
            model_name='guest',
            name='memo',
            field=models.TextField(blank=True, help_text='参加人数が複数の場合や遅れて参加の場合は記入してください'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(help_text='名前を入力して下さい', max_length=30),
        ),
    ]
